{
  "nodes": [
    {
      "x": 144.79999999999998,
      "y": 231.99999999999997,
      "roadsIn": [
        1
      ],
      "roadsOut": [
        0
      ]
    },
    {
      "x": 463.2,
      "y": 240.79999999999998,
      "roadsIn": [
        0,
        3
      ],
      "roadsOut": [
        1,
        2
      ]
    },
    {
      "x": 624.8000000000001,
      "y": 172.0,
      "roadsIn": [
        2
      ],
      "roadsOut": [
        3
      ]
    }
  ],
  "roads": [
    {
      "from": 0,
      "to": 1,
      "lanes": []
    },
    {
      "from": 1,
      "to": 0,
      "lanes": [
        {
          "signs": []
        }
      ]
    },
    {
      "from": 1,
      "to": 2,
      "lanes": []
    },
    {
      "from": 2,
      "to": 1,
      "lanes": [
        {
          "signs": []
        }
      ]
    }
  ],
  "pointsOfInterest": [],
    "start": "10:00",
    "currentTime": "10:15",
    "end": "15:00"
}