{
  "nodes": [
    {
      "x": 184.0,
      "y": 271.2,
      "roadsIn": [
        1
      ],
      "roadsOut": [
        0
      ],
      "connector": {
        "regionId": 0,
        "connectorId": 0
      }
    },
    {
      "x": 240.79999999999998,
      "y": 156.79999999999998,
      "roadsIn": [
        0,
        3
      ],
      "roadsOut": [
        1,
        2
      ],
      "connector": {
        "regionId": 0,
        "connectorId": 0
      }
    },
    {
      "x": 276.8,
      "y": 267.2,
      "roadsIn": [
        2,
        5
      ],
      "roadsOut": [
        3,
        4
      ],
      "connector": {
        "regionId": 0,
        "connectorId": 0
      }
    },
    {
      "x": 544.0,
      "y": 186.4,
      "roadsIn": [
        4
      ],
      "roadsOut": [
        5
      ],
      "connector": {
        "regionId": 0,
        "connectorId": 0
      }
    }
  ],
  "roads": [
    {
      "from": 0,
      "to": 1,
      "lanes": [
        {
          "signs": []
        }
      ]
    },
    {
      "from": 1,
      "to": 0,
      "lanes": [
        {
          "signs": []
        }
      ]
    },
    {
      "from": 1,
      "to": 2,
      "lanes": [
        {
          "signs": []
        }
      ]
    },
    {
      "from": 2,
      "to": 1,
      "lanes": [
        {
          "signs": []
        }
      ]
    },
    {
      "from": 2,
      "to": 3,
      "lanes": [
        {
          "signs": []
        }
      ]
    },
    {
      "from": 3,
      "to": 2,
      "lanes": [
        {
          "signs": []
        }
      ]
    }
  ],
  "pointsOfInterest": [],
  "width": 1000.0,
  "height": 1000.0
}